### ISSUE TITLE
fatal: invalid reference: master

### ISSUE THREAD

**Issue by avahe-kellenberger** [lourenci/github-colors#5]
It seems the branch name has been changed from `master` to something else.
How can this be installed with vim-plug?

**Comment by lourenci** [comment]
Hi, @avahe-kellenberger. I don't use Plug so I don't know what you should being doing. Have you tried to no specify any branch? This is how I configure the coloscheme with Packer: https://github.com/lourenci/dotfiles/blob/bd13912314ea72112abc3886020e6174ffdfd134/vim/.vim/lua/plugins.lua#L76

**Comment by lourenci** [comment]
I think I've renamed the main branch. Have you tried to remove the colorscheme, packer you plugin and tried to add it again?
